### ISSUE TITLE
[Error (22)] File(kolbot\d2botdropper.dbj:334) TypeError: findList.findIndex is not a function

### ISSUE THREAD

**Issue by kdiggz87** [dzik87/D2Dropper#11]
Hello, I have set everything up properly I believe using the instructions, and everything appears to be working except for when the dropper joins a game to drop an item it opens the stash and gives this error. Then stops doing anything.  It doesnt leave the game and reset after.  How can I fix this?

[Error (22)] File(kolbot\d2botdropper.dbj:334) TypeError: findList.findIndex is not a function

**Comment by kdiggz87** [comment]
https://i.ibb.co/25byDDW/err.png

**Comment by BjarkeM** [comment]
follow the guide and download the [latest kolbot](https://github.com/blizzhackers/kolbot)
