### ISSUE TITLE
Issues with logging/writing Items to DB while using Sonic

### ISSUE THREAD

**Issue by cry-d2** [dzik87/D2Dropper#16]
Greetings.

**Environment**:
SetupSonics' d2bot
Bots are running
AutoMule is running
link.bat was properly executed => linked folder to databases exist in d2b\d2bs\kolbot\databases

Char Viewer (within the D2Bot) is full of data with the items on the Mules

**My issue:**
Even though i know that Sonic is a quite "risky" (risky like crashing the whole bot) version of kolbot to merge with other parts/addons of kolbot i wanted to give it a shot. Everything is running now fine for a while and i somehow managed to import some MuleData, now i got those 43 entries in my DB which won't be more, even though i'm having now more than one mule char. (I don't know how this itemdata got there)

**_Side issue:_**
I am not able to properly use the D2BotMuleLog.dbj to log already existing Mules, that's what i do:

Fill out MuleLogger.js as good as i am able to. For test cases i just used one account filled in (for me it is line 21) "myEpicMuleName/myEpicPass/europe": ["all"]

set the LogGame to (line 25) 
LogGame: ["game", "gpass"], // ["gamename", "password"]

set up a profile which is called "MuleLogger" in D2Bot using the D2BotMuleLog.dbj(without editing it; having 664 lines)

Starting the profile.

What actually happens on starting the profile:
D2 opens up
Skipping to main menu
Idle
[D2Bot Console]: (MuleLogger) Done logging mules!
Exiting D2
Profile <Stopped>

This side issue already seems quite strange to me.

To be honest, at the moment i have no idea where the dropper actually takes its information from, i can't understand how D2Bot is holding my desired item Informations in Char Viewer (and the txt files somewhere within the D2B (sub-)folders) but the DropperDB doesn't take note of that information.

I experimented a lot with this whole setup to make it work at all, at the beginning i had some issues with setting up the AutoMule since it threw issues at me for whatever reason. I'm quite a beginner in this scene (obviously). 
I'd like to improve but im currently stuck.

Thanks in advance for your help.
If you require any more information feel free to ask. :)

regards

**Comment by dzik87** [comment]
> Fill out MuleLogger.js as good as i am able to. For test cases i just used one account filled in (for me it is line 21) "myEpicMuleName/myEpicPass/europe": ["all"]
> 
> set the LogGame to (line 25)
> LogGame: ["game", "gpass"], // ["gamename", "password"]
> 
> set up a profile which is called "MuleLogger" in D2Bot using the D2BotMuleLog.dbj(without editing it; having 664 lines)

Provided D2BotMuleLog.dbj and MuleLogger.js are modified to add items into database. What is required to log items is including `ItemDB.js` file and adding log lines (if you compare stock with modified one You will see what are those. If you do this it should start adding items to database on every mule request. Also it modify a little bit the way loggers access accounts data. I did split those for separate lists based on profilename.
```
LogAccounts: {
		"Logger1": { // mule logger profilename
			"account/password/realm": ["all"] 
		},
		"Logger2": { // mule logger profilename
			"account/password/realm": ["all"] 
		},
		"Logger3": { // mule logger profilename
			"account/password/realm": ["all"] 
		},
		"Logger4": { // mule logger profilename
			"account/password/realm": ["all"] 
		}
	},
```
That way you can use multiple muleloggers to speedup loggin process.

> To be honest, at the moment i have no idea where the dropper actually takes its information from, i can't understand how D2Bot is holding my desired item Informations in Char Viewer (and the txt files somewhere within the D2B (sub-)folders) but the DropperDB doesn't take note of that information.

This dropper does use its own database file (Items.s3db located in linked database folder).
To add items in to database they need to be logged manually for those mules what already exists.

**Comment by cry-d2** [comment]
After changing the MuleLogger.js
it turns into an error while AutoMuling:
18:06:37 (Muler) MainLoopException: Misc.skipItem is not a function (mulelogger.js #356)
18:06:38 (SonicMF) Mule didn't rejoin. Picking up items.

**Comment by dzik87** [comment]
> 18:06:37 (Muler) MainLoopException: Misc.skipItem is not a function (mulelogger.js #356)

This means nothing more than skipItem method is not defined in Mis.js file.
You can try to add it from https://github.com/blizzhackers/kolbot this version of kolbot to your local version.
It is highly recommended tho to use kolbot from link above for dropper.
