### ISSUE TITLE
"Please Select Realm !" in server

### ISSUE THREAD

**Issue by BizzaroHunter** [dzik87/D2Dropper#17]
Followed all the instructions(I think) and when I log in to the local machine to view items / drop items, it just says 

> Welcome to item manager
> and delivery system.
> Please Select Realm !

I already used automuler in the past and used mule logger for mules I had prior to using it. D2Bot has no problem getting my info in the char viewer, which it seems to pull from the kolbot/mules folder. Yet logging in to the 'server' it shows no realms, no mules, or anything.

Maybe I missed something in the config.php for apache?

Here's a pastebin of my config.php > https://pastebin.com/0GNKR2Wh

**Comment by cry-d2** [comment]
Hey, there seems to be an issue to log them to the s3db of the apache. Did you use the D2BotMule.dbj/all the other files from the repository?

As soon as there is data within your "dropper" you can select the specific realms. So i guess your only issue will be the data transfer between your bot and the s3db (database of your dropper).

(I'm having a quite similar issue, if you check out the issues.)

**Comment by BizzaroHunter** [comment]
So I couldn't find a way to get items into the database that were already, prior to having d2dropper, automuled so I simply automuled my mule account.
