### ISSUE TITLE
D2 dropper with kolbot autoplay sorc.js line 2101 General is not defined.

### ISSUE THREAD

**Issue by SnubBeef** [dzik87/D2Dropper#19]
Was able to get this to work with normal kolbot  but not with Kolbot Autoplay. The issue I receive is 

error in sorc (sorc.js line 2101): General is not defined.

this occurs as soon as the bot joins the games and loads the files. Please help.

**Comment by dzik87** [comment]
I do not know what Sorc.js is but sounds like its custom made script.

To get it to work you would manually edit files:
- default.dbj
- mulelogger.js
- D2BotMule.js

compare what is added in those vs stock kolbot and adjust your files to include same methods.

**Comment by SnubBeef** [comment]
I believe I it is just from the auto play files that I downloaded from GitHub. I made no adjustments or customizations besides adding the dropper.

**Comment by ghost** [comment]
@SnubBeef what repo did you download the files from?
