### ISSUE TITLE
Localhost - Error: Connection failed

### ISSUE THREAD

**Issue by fridayaction** [dzik87/D2Dropper#21]
Hi guys,
can anybody help me please?
I think i could manage to install the dropper like in the discription.

I downloaded and installed the dropper.
Than I edited the .htpasswd and config.php in the  C:\Apache\htdocs\ 
I copied the files from D2Dropper-main\kolbot\  subfolder to d2bs\kolbot\ and replaced the existing ones.
I got the databases-folder with same content as in C:\Apache\htdocs\ etc.
...

Everything seems normal up to here .

But I get an error message, when I'm tryig to open localhost http://127.0.0.1:666/.
("Error: Connection failed")
Does anyone know why?

**Comment by Jestah66** [comment]
Try "http://localhost:666" - That's how I connect anyway.....

**Comment by fridayaction** [comment]
I've already tried that, but it doesn't work either :(

**Comment by dzik87** [comment]
Check for errors in C:\apache\logs\error.log file

**Comment by fridayaction** [comment]
I dont have a folder c:\apache\logs\....
and no error.log file

I also checked 
C:\Apache\error\ --> here are many files
C:\Apache\htdocs\logs\ --> only one empty file: .gitkeep

**Comment by fridayaction** [comment]
i reinstalled everything and followed the instruction step by step again.
--> everything works now :D

ty for the help
