### ISSUE TITLE
Dropper doesn't remove items from db after dropping

### ISSUE THREAD

**Issue by ghost** [dzik87/D2Dropper#23]
Hi, anybody encounter this issue before?

1. Select item from interface
2. Drop items in any game
3. Items are dropped and everything is fine
4. Refresh interface -> the dropped items still shown as being in inventory.

Anybody have an idea?

**Comment by dzik87** [comment]
check logs in c:\apache\htdocs\logs\ itemdb.log file.
It should at least point where issue is

**Comment by ghost** [comment]
I didn't have itemdb.log there, but i just installed everything again (I seemed to have a problem with the databases symlink) it now works as intended :-)

thanks @dzik87 !
