### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by SnubBeef** [dzik87/D2Dropper#26]
Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at dzik87@gmail.com to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.

No Idea what happened. Any way to get around this? I tried installing whole new folder and nothing seems to work

**Comment by dzik87** [comment]
You most probably copied folder to c:\apache\htdocs instead of it's content

**Comment by ghost** [comment]
@SnubBeef did you find a solution yet? Do you have index.php in your htdocs folder?
