### ISSUE TITLE
Use on website

### ISSUE THREAD

**Issue by magace** [dzik87/D2Dropper#27]
Love the work Dzik I have managed to get almost everything working on my personal website however the CSS is not loading the drop button on my browser only on my phone.   I edited drop.php to change the json in my shared network drive however it is saving to the json in both folders on the web server and on the local folder.  I created a link to update the itemdb on the real web server.  I did have to create some new security features.    Thanks again this is so much fun to get back into.  I still need to have it update the drop logs and such.  Have you thought about making it online instead of local?

**Comment by dzik87** [comment]
Hello, 

Thanks for kind words. I do appreciate it.
Idea to make dropper was always to have it local. 
Of course there is always way to make it web based but this requires some kind of end point on server side. 
On bot side it would be as simple as creating proper socket connection and use for example POST to update database. 

I am not experienced with network security so I never really implemented anything like that.

**Comment by magace** [comment]
I got everything working now!  It ended up being some case sensitivity issues in building the navbar.  Again thanks for releasing this.
