### ISSUE TITLE
remove old mules from database

### ISSUE THREAD

**Issue by bluecereal127** [dzik87/D2Dropper#30]
How would I remove mules that are now expired (i.e., did not log in to them and they were not perm'd) from my database? I'd like to only have it show my current mules

**Comment by s0nders** [comment]
> How would I remove mules that are now expired (i.e., did not log in to them and they were not perm'd) from my database? I'd like to only have it show my current mules

Go to the admin page -> SQLite Admin -> muleAccounts then delete the accounts you'd like
