### ISSUE TITLE
MuleLogger (D2BotMuleLog.dbj) not working on fresh install of D2Dropper

### ISSUE THREAD

**Issue by jeanmroy** [dzik87/D2Dropper#37]
Hi team.

Overall, my issue is that I can't make my MuleLogger to log on battle net accounts. The script is just ending saying : 12:46:42 (MuleLog) Done logging mules!

When I look at the screen, he doesn't even click on the battle net button, to go at the logon screen, where we see login password.

****** It was working fine before I added the files from D2Dropper to Kolbot.******

# Troubleshoots :
- I've made the test by removing everything in the LogAccounts: { }, bracket, and it's reacting the same (Kolbot showing in console : 12:46:42 (MuleLog) Done logging mules!). It means the issue is in that bracket.
- Tested with a brand new install. D2botMuleLog is not working. Test yourself you will see

# Kolbot profile : 
My Kolbot profile is well using the D2BotMuleLog.dbj and has nothing in "Game info". It's pretty empty. I've set the key to use, entry script, profile name, difficulty, relm, mode..

[MuleLogger.zip](https://github.com/dzik87/D2Dropper/files/6718915/MuleLogger.zip)

# Mulerlogger.js #
	LogAccounts: {
		"Logger1": { // mule logger profilename
			"jamar-1/lolz/useast": ["all"]
		},
		"Logger2": { // mule logger profilename
			"jamar-2/lolz/useast": ["all"]
		}
	},

	LogGame: ["mypermqda", "12q"], // ["gamename", "password"]
	LogNames: true, // Put account/character name on the picture
	LogItemLevel: true, // Add item level to the picture
	LogEquipped: false, // include equipped items
	LogMerc: false, // include items merc has equipped (if alive)
	SaveScreenShot: false, // Save pictures in jpg format (saved in 'Images' folder)
	IngameTime: rand(180, 210), // (180, 210) to avoid RD, increase it to (7230, 7290) for mule perming

# ..#

I would really want to make it work !

**Comment by jeanmroy** [comment]
Edited, for more clarity.
Edited , to add troubleshoot. Added a file.

**Comment by jeanmroy** [comment]
Updated

**Comment by VikinGsX** [comment]
````
modified :

function parseInfo() {
	var i, j;
	for (i in MuleLogger.LogAccounts) {
		if (MuleLogger.LogAccounts.hasOwnProperty(i) && typeof i === "string") {
			for (j in MuleLogger.LogAccounts[i]) {
				if (MuleLogger.LogAccounts[i].hasOwnProperty(j) && typeof j === "string") {
					accounts.push(j);
					chars.push(MuleLogger.LogAccounts[i][j]);
				}
			}
		}
	}
}

````
Hey buddy, you need to modify a few lines of code, open the file "D2BotMuleLog.dbj" with an editor and search for "function parseInfo()" at about 36 lines, then delete "&& i.toLowerCase() === me.profile.toLowerCase ()", save the file and restart, you can try it

**Comment by jeanmroy** [comment]
Here is what resolved the issue.

modified :

function parseInfo() {
	var i, j;
	for (i in MuleLogger.LogAccounts) {
		if (MuleLogger.LogAccounts.hasOwnProperty(i) && typeof i === "string") {
			for (j in MuleLogger.LogAccounts[i]) {
				if (MuleLogger.LogAccounts[i].hasOwnProperty(j) && typeof j === "string") {
					accounts.push(j);
					chars.push(MuleLogger.LogAccounts[i][j]);
				}
			}
		}
	}
}

- open the file "D2BotMuleLog.dbj" with an editor and search for "function parseInfo()" at about 36 lines, then delete "&& i.toLowerCase() === me.profile.toLowerCase ()", save the file and restart, you can try it
