### ISSUE TITLE
Item Screen Shots & FT List Functions

### ISSUE THREAD

**Issue by s0nders** [dzik87/D2Dropper#6]
@Fa-b has a really awesome function built for coloring the item images and building the FT lists

any chance you'd be interested in merging his work in? 

[https://github.com/Fa-b/limedrop/blob/dev/js/itemScreenshot.js](url)

**Comment by dzik87** [comment]
If you get authors permission to use his code you can try implement it yourself. 

I didn't want to have same item tool tips as they are in d2bot.
Even if it's little bit buggy and annoying to use...
